name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.20'

    - name: Download dependencies
      run:
        go install

    - name: Run unit tests
      run:
        make test

    - name: Build release files
      run: |
        go install github.com/mitchellh/gox@latest
        make build-release

    - name: Archive release artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release-artifacts
        path: release/

  create-release:
    needs: build-release
    runs-on: ubuntu-latest
    steps:
    - name: Download release artifacts
      uses: actions/download-artifact@v3
      with:
        name: release-artifacts
        path: release/

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: 'release/*.zip'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
