name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.20'

    - name: Download dependencies
      run: go install

    - name: Run unit tests
      run: make test

    - name: Build release files
      run: make build

  terraform-provider-release:
    name: Terraform Provider Release
    uses: hashicorp/ghaction-terraform-provider-release/.github/workflows/community.yml@v4
    needs: tests
    secrets:
      gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'
      gpg-private-key-passphrase: '${{ secrets.PASSPHRASE }}'
    with:
      setup-go-version: '^1.20'
